/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as RecruitRouteImport } from './routes/recruit'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyProfileRouteImport } from './routes/company.profile'
import { Route as CompanyMessageRouteImport } from './routes/company.message'
import { Route as CompanyHistoryRouteImport } from './routes/company.history'

const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitRoute = RecruitRouteImport.update({
  id: '/recruit',
  path: '/recruit',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyMessageRoute = CompanyMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyHistoryRoute = CompanyHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CompanyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/recruit': typeof RecruitRoute
  '/service': typeof ServiceRoute
  '/company/history': typeof CompanyHistoryRoute
  '/company/message': typeof CompanyMessageRoute
  '/company/profile': typeof CompanyProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/recruit': typeof RecruitRoute
  '/service': typeof ServiceRoute
  '/company/history': typeof CompanyHistoryRoute
  '/company/message': typeof CompanyMessageRoute
  '/company/profile': typeof CompanyProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/recruit': typeof RecruitRoute
  '/service': typeof ServiceRoute
  '/company/history': typeof CompanyHistoryRoute
  '/company/message': typeof CompanyMessageRoute
  '/company/profile': typeof CompanyProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/contact'
    | '/news'
    | '/recruit'
    | '/service'
    | '/company/history'
    | '/company/message'
    | '/company/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/contact'
    | '/news'
    | '/recruit'
    | '/service'
    | '/company/history'
    | '/company/message'
    | '/company/profile'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/contact'
    | '/news'
    | '/recruit'
    | '/service'
    | '/company/history'
    | '/company/message'
    | '/company/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRouteWithChildren
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  RecruitRoute: typeof RecruitRoute
  ServiceRoute: typeof ServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruit': {
      id: '/recruit'
      path: '/recruit'
      fullPath: '/recruit'
      preLoaderRoute: typeof RecruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/profile': {
      id: '/company/profile'
      path: '/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/message': {
      id: '/company/message'
      path: '/message'
      fullPath: '/company/message'
      preLoaderRoute: typeof CompanyMessageRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/history': {
      id: '/company/history'
      path: '/history'
      fullPath: '/company/history'
      preLoaderRoute: typeof CompanyHistoryRouteImport
      parentRoute: typeof CompanyRoute
    }
  }
}

interface CompanyRouteChildren {
  CompanyHistoryRoute: typeof CompanyHistoryRoute
  CompanyMessageRoute: typeof CompanyMessageRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyHistoryRoute: CompanyHistoryRoute,
  CompanyMessageRoute: CompanyMessageRoute,
  CompanyProfileRoute: CompanyProfileRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRouteWithChildren,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  RecruitRoute: RecruitRoute,
  ServiceRoute: ServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
